### ISSUE TITLE
Not an issue; free Makefile if you wish

### ISSUE THREAD

**Issue by texadactyl** [gavinlyonsrepo/particle_fire_simulation#1]

**Comment by texadactyl** [comment]
Just ran into your project yesterday.  Below is a Makefile which will work if:
- installed at the same level as README.md
- move main.cpp into src
- rename screen.cpp to something that does not end in 'cpp' [I assume that it was the old version of Screen.cpp]



```
# --- constants
CC=g++
CFLAGS=-Wall -g -c
LDFLAGS=-Wall -g -L /usr/lib/x86_64-linux-gnu -l SDL2
SOURCES = $(wildcard ./src/*.cpp)
OBJECTS = $(SOURCES:.cpp=.o)
BIN=./bin
INCLUDES=./include
TARGET=$(BIN)/pfsim

# --- Target of build process
all:	$(TARGET)

$(TARGET):	$(OBJECTS)
	$(CC) -o $(TARGET) $(OBJECTS) $(LDFLAGS)

# Make an .o from a .cpp
%.o: %.cpp
	$(CC) $(CFLAGS) -o $@ -c $< -iquote $(INCLUDES)

# --- Cleanup
.PHONY: clean
clean:
	rm -f $(TARGET) $(OBJECTS)
```

**Comment by texadactyl** [comment]
The LDFLAGS -L specification is an x64 Ubuntu requirement.  It can obviously be amended for another environment.

**Comment by gavinlyonsrepo** [comment]
Hi 

Thank you  for this! 
I have made one small change and added a makefile to project.

Regards
